# Generated by Django 2.1.2 on 2018-10-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('working', 'working'), ('broken', 'broken'), ('fixing', 'fixing'), ('fixed', 'fixed')], default='working', max_length=7)),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('mATX', 'mATX'), ('eATX', 'eATX')], max_length=4)),
                ('socket', models.CharField(choices=[('LGA1150', 'LGA1150'), ('LGA1151', 'LGA1151'), ('FM2', 'FM2'), ('FM2+', 'FM2+')], max_length=7)),
                ('max_pci_slots', models.IntegerField()),
                ('used_pci_slots', models.IntegerField()),
                ('installed_ram_capacity', models.IntegerField()),
                ('max_ram_capacity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('working', 'working'), ('broken', 'broken'), ('fixing', 'fixing'), ('fixed', 'fixed')], default='working', max_length=7)),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('mATX', 'mATX'), ('eATX', 'eATX')], max_length=4)),
                ('trunk_type', models.CharField(choices=[('vertical', 'vertical'), ('horizontal', 'horizontal')], max_length=10)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='trunk',
            name='warranty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_center.Warranty'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='warranty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_center.Warranty'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mother_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_center.MotherBoard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='trunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_center.Trunk'),
        ),
    ]
