# Generated by Django 2.1.2 on 2018-10-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='mother_board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_center.MotherBoard'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='trunk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_center.Trunk'),
        ),
    ]
