# Generated by Django 2.1.2 on 2018-10-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0002_auto_20181021_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='trunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_center.Trunk'),
        ),
    ]
