# Generated by Django 2.1.2 on 2018-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0003_auto_20181021_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='component_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trunk',
            name='component_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
